address;source_location;insn;indent
0x1bd0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:85;ENDBR64;
0x1bd4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:85;PUSH	%RBP;
0x1bd5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:85;MOV	%RSP,%RBP;
0x1bd8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:85;CALLQ	0x741a(%RIP);
0x1bde;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;TEST	%RDI,%RDI;
0x1be1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;JE	1d0f <get_cell_velocity+0x13f>;
0x1be7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;TEST	%RSI,%RSI;
0x1bea;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;JE	1d2e <get_cell_velocity+0x15e>;
0x1bf0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;VMOVSD	0x4698(%RIP),%XMM1;
0x1bf8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;LEA	0x48(%RSI),%RAX;
0x1bfc;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;VDIVSD	%XMM0,%XMM1,%XMM0;
0x1c00;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;CMP	%RAX,%RDI;
0x1c03;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;JAE	1c0e <get_cell_velocity+0x3e>;
0x1c05;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;LEA	0x10(%RDI),%RDX;
0x1c09;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;CMP	%RDX,%RSI;
0x1c0c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;JB	1c84 <get_cell_velocity+0xb4>;
0x1c0e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVDDUP	0x8(%RSI),%XMM1;
0x1c13;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVDDUP	0x10(%RSI),%XMM2;
0x1c18;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VANDPD	0x46e0(%RIP),%XMM1,%XMM3;
0x1c20;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VANDPD	0x46e8(%RIP),%XMM2,%XMM4;
0x1c28;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVQ	0x46f0(%RIP),%XMM6;
0x1c30;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VADDPD	%XMM4,%XMM3,%XMM5;
0x1c34;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVAPD	0x46f4(%RIP),%XMM7;
0x1c3c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVAPD	0x46fc(%RIP),%XMM9;
0x1c44;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VFMADD231PD	0x18(%RSI){1to2},%XMM6,%XMM5;
0x1c4b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVAPD	0x46fd(%RIP),%XMM11;
0x1c53;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVDDUP	%XMM0,%XMM0;
0x1c57;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VFMADD132PD	0x20(%RSI){1to2},%XMM5,%XMM7;
0x1c5e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VADDPD	0x28(%RSI){1to2},%XMM7,%XMM8;
0x1c65;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VFMADD132PD	0x30(%RSI){1to2},%XMM8,%XMM9;
0x1c6c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VSUBPD	0x38(%RSI){1to2},%XMM9,%XMM10;
0x1c73;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VFMADD132PD	0x40(%RSI){1to2},%XMM10,%XMM11;
0x1c7a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VMULPD	%XMM0,%XMM11,%XMM12;
0x1c7e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VMOVUPD	%XMM12,(%RDI);
0x1c82;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:106;POP	%RBP;
0x1c83;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:106;RET;
0x1c84;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:97;MOVQ	$0,(%RDI);
0x1c8b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	0x8(%RSI),%XMM2;
0x1c90;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM2,(%RDI);
0x1c94;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VSUBSD	0x18(%RSI),%XMM2,%XMM3;
0x1c99;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM3,(%RDI);
0x1c9d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VADDSD	0x28(%RSI),%XMM3,%XMM4;
0x1ca2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM4,(%RDI);
0x1ca6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VSUBSD	0x30(%RSI),%XMM4,%XMM5;
0x1cab;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM5,(%RDI);
0x1caf;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VSUBSD	0x38(%RSI),%XMM5,%XMM6;
0x1cb4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM6,(%RDI);
0x1cb8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VADDSD	0x40(%RSI),%XMM6,%XMM7;
0x1cbd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:97;MOVQ	$0,0x8(%RDI);
0x1cc5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VMULSD	%XMM0,%XMM7,%XMM8;
0x1cc9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VMOVSD	%XMM8,(%RDI);
0x1ccd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	0x10(%RSI),%XMM9;
0x1cd2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM9,0x8(%RDI);
0x1cd7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VSUBSD	0x20(%RSI),%XMM9,%XMM10;
0x1cdc;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM10,0x8(%RDI);
0x1ce1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VADDSD	0x28(%RSI),%XMM10,%XMM11;
0x1ce6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM11,0x8(%RDI);
0x1ceb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VADDSD	0x30(%RSI),%XMM11,%XMM12;
0x1cf0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM12,0x8(%RDI);
0x1cf5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VSUBSD	0x38(%RSI),%XMM12,%XMM13;
0x1cfa;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:101;VMOVSD	%XMM13,0x8(%RDI);
0x1cff;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VSUBSD	0x40(%RSI),%XMM13,%XMM14;
0x1d04;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VMULSD	%XMM0,%XMM14,%XMM15;
0x1d08;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:104;VMOVSD	%XMM15,0x8(%RDI);
0x1d0d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:106;POP	%RBP;
0x1d0e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:106;RET;
0x1d0f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;LEA	0x43fa(%RIP),%RCX;
0x1d16;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;MOV	$0x5a,%EDX;
0x1d1b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;LEA	0x4359(%RIP),%RSI;
0x1d22;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;LEA	0x436a(%RIP),%RDI;
0x1d29;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:90;CALL	1220 <.plt.sec@start+0x50>;
0x1d2e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;LEA	0x43db(%RIP),%RCX;
0x1d35;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;MOV	$0x5b,%EDX;
0x1d3a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;LEA	0x433a(%RIP),%RSI;
0x1d41;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;LEA	0x433e(%RIP),%RDI;
0x1d48;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:91;CALL	1220 <.plt.sec@start+0x50>;
0x1d4d;:0;NOPL	(%RAX);
