address;source_location;insn;indent
0x488a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%R9D;
0x488e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;SUB	$0x8,%RSP;
0x4892;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R12D,%R9D;
0x4896;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;PUSHQ	-0x68(%RBP);
0x4899;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	(%R14),%RCX;
0x489c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R9,%R9,8),%EAX;
0x48a0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x48a2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;ADD	%RBX,%RAX;
0x48a5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	(%RCX,%RAX,8),%RDI;
0x48a9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	%R15,%R9;
0x48ac;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;XOR	%R8D,%R8D;
0x48af;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	%R13D,%ECX;
0x48b2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	0x4767(%RIP),%RDX;
0x48b9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	$0x9,%ESI;
0x48be;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;CALL	12b0 <.plt.sec@start+0xe0>;
0x48c3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%R10D;
0x48c7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;POP	%RCX;
0x48c8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R12D,%R10D;
0x48cc;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;PUSHQ	-0x68(%RBP);
0x48cf;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	(%R14),%RSI;
0x48d2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R10,%R10,8),%EAX;
0x48d6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x48d8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	0x1(%RBX,%RAX,1),%R11;
0x48dd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	(%RSI,%R11,8),%RDI;
0x48e1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	%R15,%R9;
0x48e4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;XOR	%R8D,%R8D;
0x48e7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	%R13D,%ECX;
0x48ea;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	0x472f(%RIP),%RDX;
0x48f1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	$0x9,%ESI;
0x48f6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;CALL	12b0 <.plt.sec@start+0xe0>;
0x48fb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%EDX;
0x48ff;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;POP	%RSI;
0x4900;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R12D,%EDX;
0x4904;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;PUSHQ	-0x68(%RBP);
0x4907;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	(%R14),%R8;
0x490a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDX,%RDX,8),%EAX;
0x490d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x490f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	0x2(%RBX,%RAX,1),%RDI;
0x4914;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	(%R8,%RDI,8),%RDI;
0x4918;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	%R15,%R9;
0x491b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;XOR	%R8D,%R8D;
0x491e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	%R13D,%ECX;
0x4921;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;LEA	0x46f8(%RIP),%RDX;
0x4928;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;MOV	$0x9,%ESI;
0x492d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:235;CALL	12b0 <.plt.sec@start+0xe0>;
0x4932;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;ADD	$0x3,%RBX;
0x4936;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;POP	%RDI;
0x4937;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;POP	%R8;
0x4939;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;CMP	$0x9,%RBX;
0x493d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_comm.c:234;JNE	488a <lbm_comm_ghost_exchange+0x3aa>;
