address;source_location;insn;indent
0x2a98;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DIL,%DIL;
0x2a9b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2c0f <propagation+0x1ff>;
0x2aa1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DL,%DL;
0x2aa3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2aad <propagation+0x9d>;
0x2aa5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%AL,%AL;
0x2aa7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2bd3 <propagation+0x1c3>;
0x2aad;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%CL,%CL;
0x2aaf;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2ab9 <propagation+0xa9>;
0x2ab1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DL,%DL;
0x2ab3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2c50 <propagation+0x240>;
0x2ab9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:340;INC	%ESI;
0x2abb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:340;ADD	%EBX,%R11D;
0x2abe;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:340;CMP	%ESI,%R12D;
0x2ac1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:340;JE	2bb8 <propagation+0x1a8>;
0x2ac7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;CMP	%ESI,%R12D;
0x2aca;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SETG	%R10B;
0x2ace;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;CMP	%R13D,%EBX;
0x2ad1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:346;VCVTSI2SD	%ESI,%XMM3,%XMM5;
0x2ad5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SETG	%DL;
0x2ad8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JLE	2ae3 <propagation+0xd3>;
0x2ada;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%R10B,%R10B;
0x2add;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2c8a <propagation+0x27a>;
0x2ae3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:346;VADDSD	%XMM1,%XMM5,%XMM7;
0x2ae7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:346;VCVTTSD2SI	%XMM7,%R8D;
0x2aeb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;MOV	%R8D,%ECX;
0x2aee;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;NOT	%ECX;
0x2af0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SHR	$0x1f,%ECX;
0x2af3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;CMP	%R12D,%R8D;
0x2af6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SETL	%DIL;
0x2afa;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;AND	%DIL,%CL;
0x2afd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2b07 <propagation+0xf7>;
0x2aff;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DL,%DL;
0x2b01;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2d39 <propagation+0x329>;
0x2b07;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;CMP	-0x2c(%RBP),%EBX;
0x2b0a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SETG	%DIL;
0x2b0e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;AND	-0x34(%RBP),%DIL;
0x2b12;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%R10B,%R10B;
0x2b15;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2b20 <propagation+0x110>;
0x2b17;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DIL,%DIL;
0x2b1a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2d75 <propagation+0x365>;
0x2b20;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:346;VSUBSD	%XMM1,%XMM5,%XMM10;
0x2b24;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:346;VCVTTSD2SI	%XMM10,%R9D;
0x2b29;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;MOV	%R9D,%EAX;
0x2b2c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;CMP	%R9D,%R12D;
0x2b2f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;NOT	%EAX;
0x2b31;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SETG	%R15B;
0x2b35;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SHR	$0x1f,%EAX;
0x2b38;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;AND	%R15D,%EAX;
0x2b3b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DL,%DL;
0x2b3d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2b47 <propagation+0x137>;
0x2b3f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%AL,%AL;
0x2b41;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2cbd <propagation+0x2ad>;
0x2b47;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;CMP	-0x30(%RBP),%EBX;
0x2b4a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;SETG	%DL;
0x2b4d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;AND	-0x38(%RBP),%DL;
0x2b50;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2b5b <propagation+0x14b>;
0x2b52;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%R10B,%R10B;
0x2b55;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2cfb <propagation+0x2eb>;
0x2b5b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%CL,%CL;
0x2b5d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JNE	2a98 <propagation+0x88>;
0x2b63;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%DIL,%DIL;
0x2b66;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2aa1 <propagation+0x91>;
0x2b6c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;TEST	%AL,%AL;
0x2b6e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:349;JE	2aa1 <propagation+0x91>;
0x2b74;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%EDI;
0x2b78;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%EDI;
0x2b7b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EDI;
0x2b7e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDI,%RDI,8),%R10D;
0x2b82;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R10D,%R15;
0x2b85;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	%EBX,%R10D;
0x2b88;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R9D,%R10D;
0x2b8c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%RDI;
0x2b8f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	-0x2c(%RBP),%R10D;
0x2b93;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x30(%RDI,%R15,8),%XMM14;
0x2b9a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R10,%R10,8),%R15D;
0x2b9e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R10;
0x2ba2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R15D,%RDI;
0x2ba5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R10),%R15;
0x2ba8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM14,0x30(%R15,%RDI,8);
0x2baf;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2aa1 <propagation+0x91>;
0x2bd3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%EAX;
0x2bd7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%EBX,%R9D;
0x2bdb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%EAX;
0x2bde;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	-0x30(%RBP),%R10D;
0x2be2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%RDI;
0x2be5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EAX;
0x2be8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R9D,%R10D;
0x2beb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RAX,%RAX,8),%EAX;
0x2bee;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R9;
0x2bf2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2bf4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x38(%RDI,%RAX,8),%XMM15;
0x2bfa;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R9),%R15;
0x2bfd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R10,%R10,8),%EAX;
0x2c01;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2c03;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM15,0x38(%R15,%RAX,8);
0x2c0a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2aad <propagation+0x9d>;
0x2c0f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%R10D;
0x2c13;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%R10D;
0x2c17;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%R10D;
0x2c1a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R10,%R10,8),%R15D;
0x2c1e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R15D,%R10;
0x2c21;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%R15;
0x2c24;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x28(%R15,%R10,8),%XMM13;
0x2c2b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	%R8D,%R10D;
0x2c2e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%EBX,%R10D;
0x2c32;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	-0x2c(%RBP),%R10D;
0x2c36;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R10,%R10,8),%R15D;
0x2c3a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R15D,%R10;
0x2c3d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R15;
0x2c41;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R15),%R15;
0x2c44;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM13,0x28(%R15,%R10,8);
0x2c4b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2b63 <propagation+0x153>;
0x2c50;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%ECX;
0x2c54;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%EBX,%R8D;
0x2c58;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%ECX;
0x2c5b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	-0x30(%RBP),%EDI;
0x2c5e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%RDX;
0x2c61;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%ECX;
0x2c64;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R8D,%EDI;
0x2c67;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RCX,%RCX,8),%EAX;
0x2c6a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R8;
0x2c6e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2c70;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x40(%RDX,%RAX,8),%XMM0;
0x2c76;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R8),%R10;
0x2c79;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDI,%RDI,8),%EAX;
0x2c7c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2c7e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM0,0x40(%R10,%RAX,8);
0x2c85;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2ab9 <propagation+0xa9>;
0x2c8a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%EDI;
0x2c8e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%R8;
0x2c91;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%EDI;
0x2c94;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R15;
0x2c98;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R11,%R13,1),%R9D;
0x2c9c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EDI;
0x2c9f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDI,%RDI,8),%EAX;
0x2ca2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2ca4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	(%R8,%RAX,8),%XMM6;
0x2caa;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R15),%RCX;
0x2cad;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R9,%R9,8),%EAX;
0x2cb1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2cb3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM6,(%RCX,%RAX,8);
0x2cb8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2ae3 <propagation+0xd3>;
0x2cbd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%EDX;
0x2cc1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%EDX;
0x2cc4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EDX;
0x2cc7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDX,%RDX,8),%R15D;
0x2ccb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R15D,%RDX;
0x2cce;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%R15;
0x2cd1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x18(%R15,%RDX,8),%XMM11;
0x2cd8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	%EBX,%EDX;
0x2cda;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R9D,%EDX;
0x2cde;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EDX;
0x2ce1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDX,%RDX,8),%R15D;
0x2ce5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R15D,%RDX;
0x2ce8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R15;
0x2cec;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R15),%R15;
0x2cef;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM11,0x18(%R15,%RDX,8);
0x2cf6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2b47 <propagation+0x137>;
0x2cfb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%R10D;
0x2cff;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%R10D;
0x2d03;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%R10D;
0x2d06;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R10,%R10,8),%R15D;
0x2d0a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R15D,%R10;
0x2d0d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%R15;
0x2d10;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x20(%R15,%R10,8),%XMM12;
0x2d17;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	-0x30(%RBP),%R10D;
0x2d1b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R11,%R10,1),%R15D;
0x2d1f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R15,%R15,8),%R10D;
0x2d23;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R15;
0x2d27;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOVSXD	%R10D,%R10;
0x2d2a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R15),%R15;
0x2d2d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM12,0x20(%R15,%R10,8);
0x2d34;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2b5b <propagation+0x14b>;
0x2d39;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%R9D;
0x2d3d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	%R8D,%EDI;
0x2d40;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%R9D;
0x2d44;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%EBX,%EDI;
0x2d47;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%R15;
0x2d4a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%R9D;
0x2d4d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R9,%R9,8),%EAX;
0x2d51;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R9;
0x2d55;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2d57;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EDI;
0x2d5a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x8(%R15,%RAX,8),%XMM8;
0x2d61;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R9),%R15;
0x2d64;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RDI,%RDI,8),%EAX;
0x2d67;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2d69;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM8,0x8(%R15,%RAX,8);
0x2d70;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2b07 <propagation+0xf7>;
0x2d75;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R14),%EAX;
0x2d79;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R14),%R9;
0x2d7c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%ESI,%EAX;
0x2d7f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	-0x2c(%RBP),%R15D;
0x2d83;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R13D,%EAX;
0x2d86;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RAX,%RAX,8),%EAX;
0x2d89;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2d8b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	0x10(%R9,%RAX,8),%XMM9;
0x2d92;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	-0x40(%RBP),%R9;
0x2d96;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%R11D,%R15D;
0x2d99;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R15,%R15,8),%EAX;
0x2d9d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;MOV	(%R9),%R15;
0x2da0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x2da2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;VMOVSD	%XMM9,0x10(%R15,%RAX,8);
0x2da9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_phys.c:350;JMP	2b20 <propagation+0x110>;
