address;source_location;insn;indent
0x319b;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	-0x70(%RBP),%RCX;
0x319f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	0x62a3(%RIP),%ESI;
0x31a5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	0x4(%RCX),%EDI;
0x31a8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;ADD	%EBX,%EDI;
0x31aa;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;CALL	2210 <helper_compute_poiseuille>;
0x31af;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R13),%EAX;
0x31b3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	(%R13),%RDI;
0x31b7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R14D,%EAX;
0x31bb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	0x30ce(%RIP),%R9;
0x31c2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;VMOVSD	%XMM0,-0x50(%RBP);
0x31c7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	%EAX,%ESI;
0x31c9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%EBX,%ESI;
0x31cb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RSI,%RSI,8),%EAX;
0x31ce;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x31d0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;ADD	%R12,%RAX;
0x31d3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;LEA	(%RDI,%RAX,8),%R8;
0x31d7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x68(%RBP),%RDI;
0x31db;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	%R12D,%ESI;
0x31de;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;VMOVQ	%R9,%XMM0;
0x31e3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	%R8,-0x78(%RBP);
0x31e7;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;CALL	1d50 <compute_equilibrium_profile>;
0x31ec;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;MOV	0xc(%R15),%EAX;
0x31f0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x78(%RBP),%R10;
0x31f4;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;IMUL	%R14D,%EAX;
0x31f8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:87;MOV	(%R15),%R11;
0x31fb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;VMOVSD	%XMM0,(%R10);
0x3200;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;ADD	%EBX,%EAX;
0x3202;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;CLTQ;
0x3204;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:87;MOVL	$0,(%R11,%RAX,4);
0x320c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	-0x70(%RBP),%RCX;
0x3210;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;LEA	0x1(%R12),%RDX;
0x3215;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	0x4(%RCX),%EDI;
0x3218;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	0x622a(%RIP),%ESI;
0x321e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;ADD	%EBX,%EDI;
0x3220;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;MOV	%RDX,-0x78(%RBP);
0x3224;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;CALL	2210 <helper_compute_poiseuille>;
0x3229;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R13),%EAX;
0x322d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x78(%RBP),%R8;
0x3231;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R14D,%EAX;
0x3235;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	(%R13),%R9;
0x3239;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	0x3050(%RIP),%R11;
0x3240;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	%EAX,%ESI;
0x3242;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%EBX,%ESI;
0x3244;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%RSI,%RSI,8),%EAX;
0x3247;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x3249;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;ADD	%R8,%RAX;
0x324c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x68(%RBP),%RDI;
0x3250;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;LEA	(%R9,%RAX,8),%R10;
0x3254;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	%R8D,%ESI;
0x3257;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;VMOVSD	%XMM0,-0x50(%RBP);
0x325c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;VMOVQ	%R11,%XMM0;
0x3261;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	%R10,-0x78(%RBP);
0x3265;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;CALL	1d50 <compute_equilibrium_profile>;
0x326a;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;MOV	0xc(%R15),%EAX;
0x326e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x78(%RBP),%RDX;
0x3272;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;IMUL	%R14D,%EAX;
0x3276;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:87;MOV	(%R15),%RCX;
0x3279;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;VMOVSD	%XMM0,(%RDX);
0x327d;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;ADD	%EBX,%EAX;
0x327f;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;CLTQ;
0x3281;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:87;MOVL	$0,(%RCX,%RAX,4);
0x3288;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	-0x70(%RBP),%RSI;
0x328c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;LEA	0x2(%R12),%RDI;
0x3291;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;MOV	%RDI,-0x78(%RBP);
0x3295;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	0x4(%RSI),%EDI;
0x3298;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;MOV	0x61aa(%RIP),%ESI;
0x329e;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;ADD	%EBX,%EDI;
0x32a0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;CALL	2210 <helper_compute_poiseuille>;
0x32a5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;MOV	0xc(%R13),%R8D;
0x32a9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x78(%RBP),%R9;
0x32ad;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;IMUL	%R14D,%R8D;
0x32b1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	(%R13),%R10;
0x32b5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	0x2fd4(%RIP),%RDX;
0x32bc;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;ADD	%EBX,%R8D;
0x32bf;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;LEA	(%R8,%R8,8),%EAX;
0x32c3;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:116;CLTQ;
0x32c5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;ADD	%R9,%RAX;
0x32c8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x68(%RBP),%RDI;
0x32cc;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;LEA	(%R10,%RAX,8),%R11;
0x32d0;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:84;VMOVSD	%XMM0,-0x50(%RBP);
0x32d5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	%R9D,%ESI;
0x32d8;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;VMOVQ	%RDX,%XMM0;
0x32dd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	%R11,-0x78(%RBP);
0x32e1;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;CALL	1d50 <compute_equilibrium_profile>;
0x32e6;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;MOV	0xc(%R15),%EAX;
0x32ea;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;MOV	-0x78(%RBP),%RCX;
0x32ee;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;IMUL	%R14D,%EAX;
0x32f2;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:87;MOV	(%R15),%RSI;
0x32f5;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;ADD	$0x3,%R12;
0x32f9;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;ADD	%EBX,%EAX;
0x32fb;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_struct.h:135;CLTQ;
0x32fd;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:85;VMOVSD	%XMM0,(%RCX);
0x3301;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:87;MOVL	$0,(%RSI,%RAX,4);
0x3308;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;CMP	$0x9,%R12;
0x330c;/home/anism/Téléchargements/TOP_PROJET_ETUDIANT/simu_simple_LBM/lbm_init.c:81;JNE	319b <setup_init_state_global_poiseuille_profile+0x7b>;
