_group = {
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "16,",
    addresses = "0x2da2,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 9,
    pattern = "LLLLLLLLL",
    opcodes = "VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,VMOVSD,",
    offsets = "0,8,16,24,32,40,48,56,64,",
    addresses = "0x2ca4,0x2d5a,0x2d8b,0x2cd1,0x2d10,0x2c24,0x2b93,0x2bf4,0x2c70,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 72,
    accessed_memory_nooverlap = 72,
    accessed_memory_overlap = 0,
    span = 72,
    head = 0,
    unroll_factor = 9,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "8,",
    addresses = "0x2d69,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "64,",
    addresses = "0x2c7e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 18,
    pattern = "LLLLLLLLLLLLLLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "12,0,12,0,12,0,12,0,12,0,12,0,12,0,12,0,12,0,",
    addresses = "0x2c8a,0x2c8e,0x2d39,0x2d47,0x2d75,0x2d79,0x2cbd,0x2cce,0x2cfb,0x2d0d,0x2c0f,0x2c21,0x2b74,0x2b8c,0x2bd3,0x2be2,0x2c50,0x2c5e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 108,
    accessed_memory_nooverlap = 12,
    accessed_memory_overlap = 96,
    span = 16,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "40,",
    addresses = "0x2c44,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 9,
    pattern = "LLLLLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "0,0,0,0,0,0,0,0,0,",
    addresses = "0x2caa,0x2d61,0x2d9d,0x2cec,0x2d2a,0x2c41,0x2ba5,0x2bfa,0x2c76,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 72,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 64,
    span = 8,
    head = 0,
    unroll_factor = 9,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "56,",
    addresses = "0x2c03,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "48,",
    addresses = "0x2ba8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "32,",
    addresses = "0x2d2d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "0,",
    addresses = "0x2cb3,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 19,
    pattern = "LLLLLLLLLLLLLLLLLLL",
    opcodes = "MOV,MOV,CMP,AND,MOV,MOV,MOV,CMP,AND,MOV,MOV,ADD,MOV,ADD,MOV,MOV,MOV,MOV,MOV,",
    offsets = "-64,-64,-44,-52,-44,-64,-64,-48,-56,-48,-64,-44,-64,-44,-64,-48,-64,-48,-64,",
    addresses = "0x2c94,0x2d51,0x2b07,0x2b0e,0x2d7f,0x2d92,0x2ce8,0x2b47,0x2b4d,0x2d17,0x2d23,0x2c32,0x2c3d,0x2b8f,0x2b9e,0x2bde,0x2bee,0x2c5b,0x2c6a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 106,
    accessed_memory_nooverlap = 18,
    accessed_memory_overlap = 88,
    span = 24,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSD,",
    offsets = "24,",
    addresses = "0x2cef,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
